### PR TITLE
Major overhaul

### PR DESCRIPTION
**Pull request by RTbecard**
Previously, this was page was just reading from a remote template and adding some content on top.  There were issues with limited functionality.

I now copied the source code of that template directly into the the repo, so we can modify it to our needs.

Functionally, the site is now a bit different:
- New pages can be added by dropping `.md` files in the `/docs` folder.  Just make sure you add the correct YAML matter (see `README.md`).
- I added a navigation sidebar.  Any page with the YAML tag `nav: true` will be listed here automatically.
- I added a example of a new page (this is just an illustrative example).

### CODE REVIEW

**Comment by RTbecard** [comment]
Also,  the `README.md` no longer holds website content, but now functions as an actual README.  I've placed instructions on how to add pages and modify the site configuration in there.

**Comment by JennaVergeynst** [comment]
Thanks for the modifications! Should I wait bug fixes before to merge pull request or not?

**Comment by RTbecard** [comment]
I think I got all the bugs... was a bit annoying, as the bugs were on the github side of things... so I wouldn't know if its fixed until I make a new push to the repo, hence the commit messages are a bit vague about my progress.

Just make sure to preview it before accepting (I guess you can view it on [my fork](https://rtbecard.github.io/APosTel-team.github.io/)).

**Comment by JennaVergeynst** [comment]
Great. Thanks also for adding your R package. However I'm not sure about the addition of the page 'software tools', because, well... it's all about software tools (or in general shared code) also on the current home page. Is there any possibility to fit the references to your package in the original structure? (i.e. within the parts Preprocessing / Data preparation / Positioning). Then the different pages could be these 3 parts... If not, we should maybe rethink the structure... e.g. Preprocessing / Data prep / Positioning / All-in-one packages. And in this case refer for instance in the Preprocessing-HTI part to your all-in-one-HTI-package... What do you think?

**Comment by RTbecard** [comment]
I won't be offended if you change the layout :p   I just wrote something out so I could give some examples of how material can be presented (different pagers for different sections, and linking to the latest compiled vignettes for packages).  And I agree I gave that page a terrible title :)

But ya, I see this is going to be quite difficult to organize in a sensible manner... as the scope of the various contributions will vary greatly, so organizing by preprocessing/analysis,etc will result in a lot ov overlap and redundant info.  Maybe a page for packages, a page for scripts, supporting literature, etc?  I really have no idea what the best layout would be, so I feel free to accept the pull, then immediately change it to your preferred layout!

**Pull request merged**
